version: '3.6'

services:
    moebius:
        build: ./docker
        container_name: moebius
        ports:
            - "9090:8888"
        volumes:
            - ./:/opt/notebooks
        command: >-
            jupyter notebook 
            --notebook-dir=/opt/notebooks --ip='*' --port=8888 
            --no-browser --allow-root
